apiVersion: v1
kind: Service
metadata:
  name: toy-svc
  namespace: local
  labels:
    app.kubernetes.io/name: toy
    app.kubernetes.io/instance: toy-myapp 
    app.kubernetes.io/component: app
spec:
  type: NodePort
  port:
  - targetPort: 8080
    port: 8080
    nodePort: 30008
  selector:
    app.kubernetes.io/instance: toy-myapp 
    app.kubernetes.io/component: app